controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# ajouter par moi
app_login:
    path: /login
    controller: App\Controller\SecurityController::login
app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
ventes:
    path: /ventes
    controller: App\Controller\MainController::timeline